name: Spotistats-CI-DEV

on:
  push:
    branches: [ "dev" ]

jobs:
  build-backend:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: |
          jhell/spotistats:dev-${{ github.sha }}
  
  build-frontend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            jhell/spotistats-ui:dev-${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Update api deployment image
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          version: v1.29.1
          command: set image deployment/spotistats-api-dev-deployment spotistats-api=jhell/spotistats:dev-${{ github.sha }}
      - name: Update ui deployment image
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          version: v1.29.1
          command: set image deployment/spotistats-ui-dev-deployment spotistats-ui=jhell/spotistats-ui:dev-${{ github.sha }}
