name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --platform linux/arm64/v8 --tag jhell/spotistats:${GITHUB_SHA} --tag jhell/spotistats:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          jhell/spotistats:${GITHUB_SHA}
          jhell/spotistats:latest
